# playbook_containers.yml



---



- hosts: localhost



  connection: local



  tasks:

    - name: Start container 1             

      docker_container:

        name: "container1"

        recreate: yes

        image: apppoei:latest

        state: started

        ports:

         - "5001:5000"



    - name: Start container 2

      docker_container:

        name: "container2"

        recreate: yes

        image: apppoei:latest

        state: started

        ports:

         - "5002:5000"



    - name: Start container 3

      docker_container:

        name: "container3"

        recreate: yes

        image: apppoei:latest

        state: started

        ports:

         - "5003:5000"





    - name: start lb

      docker_container:

        name: "lb"

        recreate: yes

        image: nginxlb:latest

        state: started

        ports:

         - "8090:80"


